### ISSUE TITLE
linuxgamingcentral.com gone?

### ISSUE THREAD

**Issue by sonic2kk** [linuxgamingcentral/website#6]
Maybe not the right place for this as this is the repo for the site code and not an "issue tracker" for the website, butI noticed the LinuxGamingCentral site has been down for a couple of days. The [Mastodon](https://mastodon.social/@linuxgamingcentral) account is also gone, as well as a [Twitter](https://twitter.com/linuxgamingctr) account (though not sure how long this has been gone for, don't recall seeing a Twitter link on the site).

Not sure if something was announced which I happened to miss :-)

**Comment by linuxgamingcentral** [comment]
Website should be [back up](https://linuxgamingcentral.com/).
